language: node_js
sudo: false
node_js:
- '6'
before_install:
- npm install coveralls
- npm install npm@5.6 -g
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libstdc++6
after_script:
- npm run coverage
